### ISSUE TITLE
[question] how to use the new asset modules with inline requires like you could with raw loader

### ISSUE THREAD

**Issue by spence-s** [webpack/raw-loader#107]
Documentation Is:

- [x] Missing
- [x] Needed
- [x] Confusing
- [x] Not Sure?

### Please Explain in Detail...

I want to know if we can use the new asset modules like raw-loader inline like this `import txt from 'raw-loader!./file.txt';`

I find the inline useful in certain situations - and this module is deprecated and there isn't anything documented to replace the above syntax.

### Your Proposal for Changes

Please document how to achieve the inline raw require with the new asset modules.

**Comment by alexander-akait** [comment]
No docs, because we want to be as close as possible to browser and Node.js ESM spec, and `inline` syntax is never work in browsers or Node.js, it will be possible in future with `assert` imports, but now we don't want to create new non ESM syntax, so please use `webpack.config.js`, sorry, in long term `inline` syntax should be fully removed, because it was a big mistake

**Comment by spence-s** [comment]
Thank you - I will be phasing out my usage of them then.

**Comment by alexander-akait** [comment]
You can track `assert` here https://github.com/webpack/webpack/issues/11917

**Comment by alexander-akait** [comment]
I hope we can introduce new ES modules features in near future and will be fully compatibility with Node.js/browsers/etc targets

**Comment by alexander-akait** [comment]
@Spence-S Anyway I think I found solution:

```js
import txt from './file.txt?raw';
```

and put in webpack.config.js:

```js
{
  // Maybe test need provided too
  type: "asset/source",
  resourceQuery: /raw/
}
```

Should work

**Comment by alexander-akait** [comment]
ES modules compatibility + the same approach without extra configurations

**Comment by spence-s** [comment]
@alexander-akait thank you for this! Good stuff!

**Comment by alexander-akait** [comment]
@Spence-S I think we need docs it https://webpack.js.org/guides/asset-modules/ , do you want to help?

**Comment by spence-s** [comment]
Sure, I can add that 👍🏻
