### ISSUE TITLE
Different behavior when using webpack2 

### ISSUE THREAD

**Issue by priyajeet** [webpack/raw-loader#14]
I am using the raw-loader to inline some SVG / HTML as raw strings. With webpack it worked fine. With webpack2 I am getting:

```html
<button>
module.exports = __webpack_public_path__ + "src/lib/icons/button.svg";
</button>
```

while with webpack1:

```html

<button>
<svg>
    ...
</svg>
</button>
```

**Comment by priyajeet** [comment]
User error, sorry

**Comment by rainboxx** [comment]
Could you tell us what was actually wrong? I have the same issue, still looking for what I did wrong 😉.

**Comment by rainboxx** [comment]
Well, not the same, but I get `module.exports = "data:image/svg+xml;base64,PHN2ZyB2aW...` and I assume that, if your issue was a wrong handling of webpack, it might be similar.

**Comment by priyajeet** [comment]
My error was that I had "svg" extension accidentally listed in the file-loader entry also. An oversight.
