### ISSUE TITLE
Isomorphic?

### ISSUE THREAD

**Issue by tomekwi** [webpack/raw-loader#5]
Hi,

I’ve written an isomorphic shim for *raw-loader*. Works in node and such. [*node-raw*](https://github.com/tomekwi/node-raw). It’s there mainly for the purpose of testing and rapid development.

@webpack would you mind mentioning it in this project?

**Comment by StevenIseki** [comment]
👍

**Comment by SpaceK33z** [comment]
Closing since the project is deprecated. I also think it's not that relevant for this loader.
