### ISSUE TITLE
unable to use line-breaks?

### ISSUE THREAD

**Issue by sunyang713** [webpack/raw-loader#6]
How could I use this loader to load a .txt where I would like to preserve the line-breaks?

**Comment by yotamDvir** [comment]
It actually does preserve the line-breaks. You can use `importedTxt.split('\n')` to get an array of the lines.
I faced the same issue when rendering in React.js, but the "problem" was with React.js, not this loader.

**Comment by sunyang713** [comment]
hey, thanks! that's a good solution.
